# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34a99339f1aa3d0926039dbfbe887a455f97566f93af4a26c51ac32f4a29ff392ae2debc2c6f23324a0ae300558e183e0a586fa514197e343a23383f4e3f3c1f

test:
  secret_key_base: 669a79758f4ea39bb4e470c095cb4865dd7058fb3ddaf7257453f12e14937ad6ba791128d0045baed8cbe1d5f1c3989d3453fc80eb3a05d2eacfdc0efbcf1dff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
